// source: envoy/api/v2/core/address.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var envoy_api_v2_core_socket_option_pb = require('../../../../envoy/api/v2/core/socket_option_pb.js');
goog.object.extend(proto, envoy_api_v2_core_socket_option_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var udpa_annotations_migrate_pb = require('../../../../udpa/annotations/migrate_pb.js');
goog.object.extend(proto, udpa_annotations_migrate_pb);
var udpa_annotations_status_pb = require('../../../../udpa/annotations/status_pb.js');
goog.object.extend(proto, udpa_annotations_status_pb);
var validate_validate_pb = require('../../../../validate/validate_pb.js');
goog.object.extend(proto, validate_validate_pb);
goog.exportSymbol('proto.envoy.api.v2.core.Address', null, global);
goog.exportSymbol('proto.envoy.api.v2.core.Address.AddressCase', null, global);
goog.exportSymbol('proto.envoy.api.v2.core.BindConfig', null, global);
goog.exportSymbol('proto.envoy.api.v2.core.CidrRange', null, global);
goog.exportSymbol('proto.envoy.api.v2.core.Pipe', null, global);
goog.exportSymbol('proto.envoy.api.v2.core.SocketAddress', null, global);
goog.exportSymbol('proto.envoy.api.v2.core.SocketAddress.PortSpecifierCase', null, global);
goog.exportSymbol('proto.envoy.api.v2.core.SocketAddress.Protocol', null, global);
goog.exportSymbol('proto.envoy.api.v2.core.TcpKeepalive', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.api.v2.core.Pipe = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.envoy.api.v2.core.Pipe, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.api.v2.core.Pipe.displayName = 'proto.envoy.api.v2.core.Pipe';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.api.v2.core.SocketAddress = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.envoy.api.v2.core.SocketAddress.oneofGroups_);
};
goog.inherits(proto.envoy.api.v2.core.SocketAddress, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.api.v2.core.SocketAddress.displayName = 'proto.envoy.api.v2.core.SocketAddress';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.api.v2.core.TcpKeepalive = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.envoy.api.v2.core.TcpKeepalive, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.api.v2.core.TcpKeepalive.displayName = 'proto.envoy.api.v2.core.TcpKeepalive';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.api.v2.core.BindConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.envoy.api.v2.core.BindConfig.repeatedFields_, null);
};
goog.inherits(proto.envoy.api.v2.core.BindConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.api.v2.core.BindConfig.displayName = 'proto.envoy.api.v2.core.BindConfig';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.api.v2.core.Address = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.envoy.api.v2.core.Address.oneofGroups_);
};
goog.inherits(proto.envoy.api.v2.core.Address, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.api.v2.core.Address.displayName = 'proto.envoy.api.v2.core.Address';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.api.v2.core.CidrRange = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.envoy.api.v2.core.CidrRange, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.api.v2.core.CidrRange.displayName = 'proto.envoy.api.v2.core.CidrRange';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.api.v2.core.Pipe.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.api.v2.core.Pipe.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.api.v2.core.Pipe} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.core.Pipe.toObject = function(includeInstance, msg) {
  var f, obj = {
    path: jspb.Message.getFieldWithDefault(msg, 1, ""),
    mode: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.api.v2.core.Pipe}
 */
proto.envoy.api.v2.core.Pipe.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.api.v2.core.Pipe;
  return proto.envoy.api.v2.core.Pipe.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.api.v2.core.Pipe} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.api.v2.core.Pipe}
 */
proto.envoy.api.v2.core.Pipe.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.api.v2.core.Pipe.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.api.v2.core.Pipe.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.api.v2.core.Pipe} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.core.Pipe.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMode();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
};


/**
 * optional string path = 1;
 * @return {string}
 */
proto.envoy.api.v2.core.Pipe.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.envoy.api.v2.core.Pipe} returns this
 */
proto.envoy.api.v2.core.Pipe.prototype.setPath = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint32 mode = 2;
 * @return {number}
 */
proto.envoy.api.v2.core.Pipe.prototype.getMode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.envoy.api.v2.core.Pipe} returns this
 */
proto.envoy.api.v2.core.Pipe.prototype.setMode = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.envoy.api.v2.core.SocketAddress.oneofGroups_ = [[3,4]];

/**
 * @enum {number}
 */
proto.envoy.api.v2.core.SocketAddress.PortSpecifierCase = {
  PORT_SPECIFIER_NOT_SET: 0,
  PORT_VALUE: 3,
  NAMED_PORT: 4
};

/**
 * @return {proto.envoy.api.v2.core.SocketAddress.PortSpecifierCase}
 */
proto.envoy.api.v2.core.SocketAddress.prototype.getPortSpecifierCase = function() {
  return /** @type {proto.envoy.api.v2.core.SocketAddress.PortSpecifierCase} */(jspb.Message.computeOneofCase(this, proto.envoy.api.v2.core.SocketAddress.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.api.v2.core.SocketAddress.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.api.v2.core.SocketAddress.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.api.v2.core.SocketAddress} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.core.SocketAddress.toObject = function(includeInstance, msg) {
  var f, obj = {
    protocol: jspb.Message.getFieldWithDefault(msg, 1, 0),
    address: jspb.Message.getFieldWithDefault(msg, 2, ""),
    portValue: jspb.Message.getFieldWithDefault(msg, 3, 0),
    namedPort: jspb.Message.getFieldWithDefault(msg, 4, ""),
    resolverName: jspb.Message.getFieldWithDefault(msg, 5, ""),
    ipv4Compat: jspb.Message.getBooleanFieldWithDefault(msg, 6, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.api.v2.core.SocketAddress}
 */
proto.envoy.api.v2.core.SocketAddress.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.api.v2.core.SocketAddress;
  return proto.envoy.api.v2.core.SocketAddress.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.api.v2.core.SocketAddress} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.api.v2.core.SocketAddress}
 */
proto.envoy.api.v2.core.SocketAddress.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.envoy.api.v2.core.SocketAddress.Protocol} */ (reader.readEnum());
      msg.setProtocol(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddress(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPortValue(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setNamedPort(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setResolverName(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIpv4Compat(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.api.v2.core.SocketAddress.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.api.v2.core.SocketAddress.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.api.v2.core.SocketAddress} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.core.SocketAddress.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProtocol();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getAddress();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getResolverName();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getIpv4Compat();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.envoy.api.v2.core.SocketAddress.Protocol = {
  TCP: 0,
  UDP: 1
};

/**
 * optional Protocol protocol = 1;
 * @return {!proto.envoy.api.v2.core.SocketAddress.Protocol}
 */
proto.envoy.api.v2.core.SocketAddress.prototype.getProtocol = function() {
  return /** @type {!proto.envoy.api.v2.core.SocketAddress.Protocol} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.envoy.api.v2.core.SocketAddress.Protocol} value
 * @return {!proto.envoy.api.v2.core.SocketAddress} returns this
 */
proto.envoy.api.v2.core.SocketAddress.prototype.setProtocol = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string address = 2;
 * @return {string}
 */
proto.envoy.api.v2.core.SocketAddress.prototype.getAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.envoy.api.v2.core.SocketAddress} returns this
 */
proto.envoy.api.v2.core.SocketAddress.prototype.setAddress = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional uint32 port_value = 3;
 * @return {number}
 */
proto.envoy.api.v2.core.SocketAddress.prototype.getPortValue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.envoy.api.v2.core.SocketAddress} returns this
 */
proto.envoy.api.v2.core.SocketAddress.prototype.setPortValue = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.envoy.api.v2.core.SocketAddress.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.envoy.api.v2.core.SocketAddress} returns this
 */
proto.envoy.api.v2.core.SocketAddress.prototype.clearPortValue = function() {
  return jspb.Message.setOneofField(this, 3, proto.envoy.api.v2.core.SocketAddress.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.api.v2.core.SocketAddress.prototype.hasPortValue = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string named_port = 4;
 * @return {string}
 */
proto.envoy.api.v2.core.SocketAddress.prototype.getNamedPort = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.envoy.api.v2.core.SocketAddress} returns this
 */
proto.envoy.api.v2.core.SocketAddress.prototype.setNamedPort = function(value) {
  return jspb.Message.setOneofField(this, 4, proto.envoy.api.v2.core.SocketAddress.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.envoy.api.v2.core.SocketAddress} returns this
 */
proto.envoy.api.v2.core.SocketAddress.prototype.clearNamedPort = function() {
  return jspb.Message.setOneofField(this, 4, proto.envoy.api.v2.core.SocketAddress.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.api.v2.core.SocketAddress.prototype.hasNamedPort = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string resolver_name = 5;
 * @return {string}
 */
proto.envoy.api.v2.core.SocketAddress.prototype.getResolverName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.envoy.api.v2.core.SocketAddress} returns this
 */
proto.envoy.api.v2.core.SocketAddress.prototype.setResolverName = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional bool ipv4_compat = 6;
 * @return {boolean}
 */
proto.envoy.api.v2.core.SocketAddress.prototype.getIpv4Compat = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.envoy.api.v2.core.SocketAddress} returns this
 */
proto.envoy.api.v2.core.SocketAddress.prototype.setIpv4Compat = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.api.v2.core.TcpKeepalive.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.api.v2.core.TcpKeepalive.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.api.v2.core.TcpKeepalive} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.core.TcpKeepalive.toObject = function(includeInstance, msg) {
  var f, obj = {
    keepaliveProbes: (f = msg.getKeepaliveProbes()) && google_protobuf_wrappers_pb.UInt32Value.toObject(includeInstance, f),
    keepaliveTime: (f = msg.getKeepaliveTime()) && google_protobuf_wrappers_pb.UInt32Value.toObject(includeInstance, f),
    keepaliveInterval: (f = msg.getKeepaliveInterval()) && google_protobuf_wrappers_pb.UInt32Value.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.api.v2.core.TcpKeepalive}
 */
proto.envoy.api.v2.core.TcpKeepalive.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.api.v2.core.TcpKeepalive;
  return proto.envoy.api.v2.core.TcpKeepalive.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.api.v2.core.TcpKeepalive} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.api.v2.core.TcpKeepalive}
 */
proto.envoy.api.v2.core.TcpKeepalive.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_wrappers_pb.UInt32Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.UInt32Value.deserializeBinaryFromReader);
      msg.setKeepaliveProbes(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.UInt32Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.UInt32Value.deserializeBinaryFromReader);
      msg.setKeepaliveTime(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.UInt32Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.UInt32Value.deserializeBinaryFromReader);
      msg.setKeepaliveInterval(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.api.v2.core.TcpKeepalive.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.api.v2.core.TcpKeepalive.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.api.v2.core.TcpKeepalive} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.core.TcpKeepalive.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKeepaliveProbes();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.UInt32Value.serializeBinaryToWriter
    );
  }
  f = message.getKeepaliveTime();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.UInt32Value.serializeBinaryToWriter
    );
  }
  f = message.getKeepaliveInterval();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.UInt32Value.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.UInt32Value keepalive_probes = 1;
 * @return {?proto.google.protobuf.UInt32Value}
 */
proto.envoy.api.v2.core.TcpKeepalive.prototype.getKeepaliveProbes = function() {
  return /** @type{?proto.google.protobuf.UInt32Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.UInt32Value, 1));
};


/**
 * @param {?proto.google.protobuf.UInt32Value|undefined} value
 * @return {!proto.envoy.api.v2.core.TcpKeepalive} returns this
*/
proto.envoy.api.v2.core.TcpKeepalive.prototype.setKeepaliveProbes = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.api.v2.core.TcpKeepalive} returns this
 */
proto.envoy.api.v2.core.TcpKeepalive.prototype.clearKeepaliveProbes = function() {
  return this.setKeepaliveProbes(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.api.v2.core.TcpKeepalive.prototype.hasKeepaliveProbes = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.UInt32Value keepalive_time = 2;
 * @return {?proto.google.protobuf.UInt32Value}
 */
proto.envoy.api.v2.core.TcpKeepalive.prototype.getKeepaliveTime = function() {
  return /** @type{?proto.google.protobuf.UInt32Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.UInt32Value, 2));
};


/**
 * @param {?proto.google.protobuf.UInt32Value|undefined} value
 * @return {!proto.envoy.api.v2.core.TcpKeepalive} returns this
*/
proto.envoy.api.v2.core.TcpKeepalive.prototype.setKeepaliveTime = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.api.v2.core.TcpKeepalive} returns this
 */
proto.envoy.api.v2.core.TcpKeepalive.prototype.clearKeepaliveTime = function() {
  return this.setKeepaliveTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.api.v2.core.TcpKeepalive.prototype.hasKeepaliveTime = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.UInt32Value keepalive_interval = 3;
 * @return {?proto.google.protobuf.UInt32Value}
 */
proto.envoy.api.v2.core.TcpKeepalive.prototype.getKeepaliveInterval = function() {
  return /** @type{?proto.google.protobuf.UInt32Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.UInt32Value, 3));
};


/**
 * @param {?proto.google.protobuf.UInt32Value|undefined} value
 * @return {!proto.envoy.api.v2.core.TcpKeepalive} returns this
*/
proto.envoy.api.v2.core.TcpKeepalive.prototype.setKeepaliveInterval = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.api.v2.core.TcpKeepalive} returns this
 */
proto.envoy.api.v2.core.TcpKeepalive.prototype.clearKeepaliveInterval = function() {
  return this.setKeepaliveInterval(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.api.v2.core.TcpKeepalive.prototype.hasKeepaliveInterval = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.envoy.api.v2.core.BindConfig.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.api.v2.core.BindConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.api.v2.core.BindConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.api.v2.core.BindConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.core.BindConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    sourceAddress: (f = msg.getSourceAddress()) && proto.envoy.api.v2.core.SocketAddress.toObject(includeInstance, f),
    freebind: (f = msg.getFreebind()) && google_protobuf_wrappers_pb.BoolValue.toObject(includeInstance, f),
    socketOptionsList: jspb.Message.toObjectList(msg.getSocketOptionsList(),
    envoy_api_v2_core_socket_option_pb.SocketOption.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.api.v2.core.BindConfig}
 */
proto.envoy.api.v2.core.BindConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.api.v2.core.BindConfig;
  return proto.envoy.api.v2.core.BindConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.api.v2.core.BindConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.api.v2.core.BindConfig}
 */
proto.envoy.api.v2.core.BindConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.envoy.api.v2.core.SocketAddress;
      reader.readMessage(value,proto.envoy.api.v2.core.SocketAddress.deserializeBinaryFromReader);
      msg.setSourceAddress(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.BoolValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.BoolValue.deserializeBinaryFromReader);
      msg.setFreebind(value);
      break;
    case 3:
      var value = new envoy_api_v2_core_socket_option_pb.SocketOption;
      reader.readMessage(value,envoy_api_v2_core_socket_option_pb.SocketOption.deserializeBinaryFromReader);
      msg.addSocketOptions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.api.v2.core.BindConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.api.v2.core.BindConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.api.v2.core.BindConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.core.BindConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSourceAddress();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.envoy.api.v2.core.SocketAddress.serializeBinaryToWriter
    );
  }
  f = message.getFreebind();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getSocketOptionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      envoy_api_v2_core_socket_option_pb.SocketOption.serializeBinaryToWriter
    );
  }
};


/**
 * optional SocketAddress source_address = 1;
 * @return {?proto.envoy.api.v2.core.SocketAddress}
 */
proto.envoy.api.v2.core.BindConfig.prototype.getSourceAddress = function() {
  return /** @type{?proto.envoy.api.v2.core.SocketAddress} */ (
    jspb.Message.getWrapperField(this, proto.envoy.api.v2.core.SocketAddress, 1));
};


/**
 * @param {?proto.envoy.api.v2.core.SocketAddress|undefined} value
 * @return {!proto.envoy.api.v2.core.BindConfig} returns this
*/
proto.envoy.api.v2.core.BindConfig.prototype.setSourceAddress = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.api.v2.core.BindConfig} returns this
 */
proto.envoy.api.v2.core.BindConfig.prototype.clearSourceAddress = function() {
  return this.setSourceAddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.api.v2.core.BindConfig.prototype.hasSourceAddress = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.BoolValue freebind = 2;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.envoy.api.v2.core.BindConfig.prototype.getFreebind = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.BoolValue, 2));
};


/**
 * @param {?proto.google.protobuf.BoolValue|undefined} value
 * @return {!proto.envoy.api.v2.core.BindConfig} returns this
*/
proto.envoy.api.v2.core.BindConfig.prototype.setFreebind = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.api.v2.core.BindConfig} returns this
 */
proto.envoy.api.v2.core.BindConfig.prototype.clearFreebind = function() {
  return this.setFreebind(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.api.v2.core.BindConfig.prototype.hasFreebind = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated SocketOption socket_options = 3;
 * @return {!Array<!proto.envoy.api.v2.core.SocketOption>}
 */
proto.envoy.api.v2.core.BindConfig.prototype.getSocketOptionsList = function() {
  return /** @type{!Array<!proto.envoy.api.v2.core.SocketOption>} */ (
    jspb.Message.getRepeatedWrapperField(this, envoy_api_v2_core_socket_option_pb.SocketOption, 3));
};


/**
 * @param {!Array<!proto.envoy.api.v2.core.SocketOption>} value
 * @return {!proto.envoy.api.v2.core.BindConfig} returns this
*/
proto.envoy.api.v2.core.BindConfig.prototype.setSocketOptionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.envoy.api.v2.core.SocketOption=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.api.v2.core.SocketOption}
 */
proto.envoy.api.v2.core.BindConfig.prototype.addSocketOptions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.envoy.api.v2.core.SocketOption, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.envoy.api.v2.core.BindConfig} returns this
 */
proto.envoy.api.v2.core.BindConfig.prototype.clearSocketOptionsList = function() {
  return this.setSocketOptionsList([]);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.envoy.api.v2.core.Address.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.envoy.api.v2.core.Address.AddressCase = {
  ADDRESS_NOT_SET: 0,
  SOCKET_ADDRESS: 1,
  PIPE: 2
};

/**
 * @return {proto.envoy.api.v2.core.Address.AddressCase}
 */
proto.envoy.api.v2.core.Address.prototype.getAddressCase = function() {
  return /** @type {proto.envoy.api.v2.core.Address.AddressCase} */(jspb.Message.computeOneofCase(this, proto.envoy.api.v2.core.Address.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.api.v2.core.Address.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.api.v2.core.Address.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.api.v2.core.Address} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.core.Address.toObject = function(includeInstance, msg) {
  var f, obj = {
    socketAddress: (f = msg.getSocketAddress()) && proto.envoy.api.v2.core.SocketAddress.toObject(includeInstance, f),
    pipe: (f = msg.getPipe()) && proto.envoy.api.v2.core.Pipe.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.api.v2.core.Address}
 */
proto.envoy.api.v2.core.Address.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.api.v2.core.Address;
  return proto.envoy.api.v2.core.Address.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.api.v2.core.Address} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.api.v2.core.Address}
 */
proto.envoy.api.v2.core.Address.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.envoy.api.v2.core.SocketAddress;
      reader.readMessage(value,proto.envoy.api.v2.core.SocketAddress.deserializeBinaryFromReader);
      msg.setSocketAddress(value);
      break;
    case 2:
      var value = new proto.envoy.api.v2.core.Pipe;
      reader.readMessage(value,proto.envoy.api.v2.core.Pipe.deserializeBinaryFromReader);
      msg.setPipe(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.api.v2.core.Address.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.api.v2.core.Address.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.api.v2.core.Address} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.core.Address.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSocketAddress();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.envoy.api.v2.core.SocketAddress.serializeBinaryToWriter
    );
  }
  f = message.getPipe();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.envoy.api.v2.core.Pipe.serializeBinaryToWriter
    );
  }
};


/**
 * optional SocketAddress socket_address = 1;
 * @return {?proto.envoy.api.v2.core.SocketAddress}
 */
proto.envoy.api.v2.core.Address.prototype.getSocketAddress = function() {
  return /** @type{?proto.envoy.api.v2.core.SocketAddress} */ (
    jspb.Message.getWrapperField(this, proto.envoy.api.v2.core.SocketAddress, 1));
};


/**
 * @param {?proto.envoy.api.v2.core.SocketAddress|undefined} value
 * @return {!proto.envoy.api.v2.core.Address} returns this
*/
proto.envoy.api.v2.core.Address.prototype.setSocketAddress = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.envoy.api.v2.core.Address.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.api.v2.core.Address} returns this
 */
proto.envoy.api.v2.core.Address.prototype.clearSocketAddress = function() {
  return this.setSocketAddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.api.v2.core.Address.prototype.hasSocketAddress = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Pipe pipe = 2;
 * @return {?proto.envoy.api.v2.core.Pipe}
 */
proto.envoy.api.v2.core.Address.prototype.getPipe = function() {
  return /** @type{?proto.envoy.api.v2.core.Pipe} */ (
    jspb.Message.getWrapperField(this, proto.envoy.api.v2.core.Pipe, 2));
};


/**
 * @param {?proto.envoy.api.v2.core.Pipe|undefined} value
 * @return {!proto.envoy.api.v2.core.Address} returns this
*/
proto.envoy.api.v2.core.Address.prototype.setPipe = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.envoy.api.v2.core.Address.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.api.v2.core.Address} returns this
 */
proto.envoy.api.v2.core.Address.prototype.clearPipe = function() {
  return this.setPipe(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.api.v2.core.Address.prototype.hasPipe = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.api.v2.core.CidrRange.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.api.v2.core.CidrRange.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.api.v2.core.CidrRange} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.core.CidrRange.toObject = function(includeInstance, msg) {
  var f, obj = {
    addressPrefix: jspb.Message.getFieldWithDefault(msg, 1, ""),
    prefixLen: (f = msg.getPrefixLen()) && google_protobuf_wrappers_pb.UInt32Value.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.api.v2.core.CidrRange}
 */
proto.envoy.api.v2.core.CidrRange.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.api.v2.core.CidrRange;
  return proto.envoy.api.v2.core.CidrRange.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.api.v2.core.CidrRange} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.api.v2.core.CidrRange}
 */
proto.envoy.api.v2.core.CidrRange.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddressPrefix(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.UInt32Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.UInt32Value.deserializeBinaryFromReader);
      msg.setPrefixLen(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.api.v2.core.CidrRange.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.api.v2.core.CidrRange.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.api.v2.core.CidrRange} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.core.CidrRange.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddressPrefix();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPrefixLen();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.UInt32Value.serializeBinaryToWriter
    );
  }
};


/**
 * optional string address_prefix = 1;
 * @return {string}
 */
proto.envoy.api.v2.core.CidrRange.prototype.getAddressPrefix = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.envoy.api.v2.core.CidrRange} returns this
 */
proto.envoy.api.v2.core.CidrRange.prototype.setAddressPrefix = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.UInt32Value prefix_len = 2;
 * @return {?proto.google.protobuf.UInt32Value}
 */
proto.envoy.api.v2.core.CidrRange.prototype.getPrefixLen = function() {
  return /** @type{?proto.google.protobuf.UInt32Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.UInt32Value, 2));
};


/**
 * @param {?proto.google.protobuf.UInt32Value|undefined} value
 * @return {!proto.envoy.api.v2.core.CidrRange} returns this
*/
proto.envoy.api.v2.core.CidrRange.prototype.setPrefixLen = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.api.v2.core.CidrRange} returns this
 */
proto.envoy.api.v2.core.CidrRange.prototype.clearPrefixLen = function() {
  return this.setPrefixLen(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.api.v2.core.CidrRange.prototype.hasPrefixLen = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.envoy.api.v2.core);
