// source: envoy/api/v2/auth/tls.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var envoy_api_v2_auth_common_pb = require('../../../../envoy/api/v2/auth/common_pb.js');
goog.object.extend(proto, envoy_api_v2_auth_common_pb);
var envoy_api_v2_auth_secret_pb = require('../../../../envoy/api/v2/auth/secret_pb.js');
goog.object.extend(proto, envoy_api_v2_auth_secret_pb);
var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
goog.object.extend(proto, google_protobuf_duration_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var udpa_annotations_migrate_pb = require('../../../../udpa/annotations/migrate_pb.js');
goog.object.extend(proto, udpa_annotations_migrate_pb);
var udpa_annotations_status_pb = require('../../../../udpa/annotations/status_pb.js');
goog.object.extend(proto, udpa_annotations_status_pb);
var validate_validate_pb = require('../../../../validate/validate_pb.js');
goog.object.extend(proto, validate_validate_pb);
goog.exportSymbol('proto.envoy.api.v2.auth.CommonTlsContext', null, global);
goog.exportSymbol('proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext', null, global);
goog.exportSymbol('proto.envoy.api.v2.auth.CommonTlsContext.ValidationContextTypeCase', null, global);
goog.exportSymbol('proto.envoy.api.v2.auth.DownstreamTlsContext', null, global);
goog.exportSymbol('proto.envoy.api.v2.auth.DownstreamTlsContext.SessionTicketKeysTypeCase', null, global);
goog.exportSymbol('proto.envoy.api.v2.auth.UpstreamTlsContext', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.api.v2.auth.UpstreamTlsContext = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.envoy.api.v2.auth.UpstreamTlsContext, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.api.v2.auth.UpstreamTlsContext.displayName = 'proto.envoy.api.v2.auth.UpstreamTlsContext';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.api.v2.auth.DownstreamTlsContext = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.envoy.api.v2.auth.DownstreamTlsContext.oneofGroups_);
};
goog.inherits(proto.envoy.api.v2.auth.DownstreamTlsContext, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.api.v2.auth.DownstreamTlsContext.displayName = 'proto.envoy.api.v2.auth.DownstreamTlsContext';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.api.v2.auth.CommonTlsContext = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.envoy.api.v2.auth.CommonTlsContext.repeatedFields_, proto.envoy.api.v2.auth.CommonTlsContext.oneofGroups_);
};
goog.inherits(proto.envoy.api.v2.auth.CommonTlsContext, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.api.v2.auth.CommonTlsContext.displayName = 'proto.envoy.api.v2.auth.CommonTlsContext';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext.displayName = 'proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.api.v2.auth.UpstreamTlsContext.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.api.v2.auth.UpstreamTlsContext.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.api.v2.auth.UpstreamTlsContext} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.auth.UpstreamTlsContext.toObject = function(includeInstance, msg) {
  var f, obj = {
    commonTlsContext: (f = msg.getCommonTlsContext()) && proto.envoy.api.v2.auth.CommonTlsContext.toObject(includeInstance, f),
    sni: jspb.Message.getFieldWithDefault(msg, 2, ""),
    allowRenegotiation: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    maxSessionKeys: (f = msg.getMaxSessionKeys()) && google_protobuf_wrappers_pb.UInt32Value.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.api.v2.auth.UpstreamTlsContext}
 */
proto.envoy.api.v2.auth.UpstreamTlsContext.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.api.v2.auth.UpstreamTlsContext;
  return proto.envoy.api.v2.auth.UpstreamTlsContext.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.api.v2.auth.UpstreamTlsContext} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.api.v2.auth.UpstreamTlsContext}
 */
proto.envoy.api.v2.auth.UpstreamTlsContext.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.envoy.api.v2.auth.CommonTlsContext;
      reader.readMessage(value,proto.envoy.api.v2.auth.CommonTlsContext.deserializeBinaryFromReader);
      msg.setCommonTlsContext(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSni(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAllowRenegotiation(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.UInt32Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.UInt32Value.deserializeBinaryFromReader);
      msg.setMaxSessionKeys(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.api.v2.auth.UpstreamTlsContext.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.api.v2.auth.UpstreamTlsContext.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.api.v2.auth.UpstreamTlsContext} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.auth.UpstreamTlsContext.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCommonTlsContext();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.envoy.api.v2.auth.CommonTlsContext.serializeBinaryToWriter
    );
  }
  f = message.getSni();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAllowRenegotiation();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getMaxSessionKeys();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.UInt32Value.serializeBinaryToWriter
    );
  }
};


/**
 * optional CommonTlsContext common_tls_context = 1;
 * @return {?proto.envoy.api.v2.auth.CommonTlsContext}
 */
proto.envoy.api.v2.auth.UpstreamTlsContext.prototype.getCommonTlsContext = function() {
  return /** @type{?proto.envoy.api.v2.auth.CommonTlsContext} */ (
    jspb.Message.getWrapperField(this, proto.envoy.api.v2.auth.CommonTlsContext, 1));
};


/**
 * @param {?proto.envoy.api.v2.auth.CommonTlsContext|undefined} value
 * @return {!proto.envoy.api.v2.auth.UpstreamTlsContext} returns this
*/
proto.envoy.api.v2.auth.UpstreamTlsContext.prototype.setCommonTlsContext = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.api.v2.auth.UpstreamTlsContext} returns this
 */
proto.envoy.api.v2.auth.UpstreamTlsContext.prototype.clearCommonTlsContext = function() {
  return this.setCommonTlsContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.api.v2.auth.UpstreamTlsContext.prototype.hasCommonTlsContext = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string sni = 2;
 * @return {string}
 */
proto.envoy.api.v2.auth.UpstreamTlsContext.prototype.getSni = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.envoy.api.v2.auth.UpstreamTlsContext} returns this
 */
proto.envoy.api.v2.auth.UpstreamTlsContext.prototype.setSni = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bool allow_renegotiation = 3;
 * @return {boolean}
 */
proto.envoy.api.v2.auth.UpstreamTlsContext.prototype.getAllowRenegotiation = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.envoy.api.v2.auth.UpstreamTlsContext} returns this
 */
proto.envoy.api.v2.auth.UpstreamTlsContext.prototype.setAllowRenegotiation = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional google.protobuf.UInt32Value max_session_keys = 4;
 * @return {?proto.google.protobuf.UInt32Value}
 */
proto.envoy.api.v2.auth.UpstreamTlsContext.prototype.getMaxSessionKeys = function() {
  return /** @type{?proto.google.protobuf.UInt32Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.UInt32Value, 4));
};


/**
 * @param {?proto.google.protobuf.UInt32Value|undefined} value
 * @return {!proto.envoy.api.v2.auth.UpstreamTlsContext} returns this
*/
proto.envoy.api.v2.auth.UpstreamTlsContext.prototype.setMaxSessionKeys = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.api.v2.auth.UpstreamTlsContext} returns this
 */
proto.envoy.api.v2.auth.UpstreamTlsContext.prototype.clearMaxSessionKeys = function() {
  return this.setMaxSessionKeys(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.api.v2.auth.UpstreamTlsContext.prototype.hasMaxSessionKeys = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.oneofGroups_ = [[4,5,7]];

/**
 * @enum {number}
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.SessionTicketKeysTypeCase = {
  SESSION_TICKET_KEYS_TYPE_NOT_SET: 0,
  SESSION_TICKET_KEYS: 4,
  SESSION_TICKET_KEYS_SDS_SECRET_CONFIG: 5,
  DISABLE_STATELESS_SESSION_RESUMPTION: 7
};

/**
 * @return {proto.envoy.api.v2.auth.DownstreamTlsContext.SessionTicketKeysTypeCase}
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.getSessionTicketKeysTypeCase = function() {
  return /** @type {proto.envoy.api.v2.auth.DownstreamTlsContext.SessionTicketKeysTypeCase} */(jspb.Message.computeOneofCase(this, proto.envoy.api.v2.auth.DownstreamTlsContext.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.api.v2.auth.DownstreamTlsContext.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.api.v2.auth.DownstreamTlsContext} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.toObject = function(includeInstance, msg) {
  var f, obj = {
    commonTlsContext: (f = msg.getCommonTlsContext()) && proto.envoy.api.v2.auth.CommonTlsContext.toObject(includeInstance, f),
    requireClientCertificate: (f = msg.getRequireClientCertificate()) && google_protobuf_wrappers_pb.BoolValue.toObject(includeInstance, f),
    requireSni: (f = msg.getRequireSni()) && google_protobuf_wrappers_pb.BoolValue.toObject(includeInstance, f),
    sessionTicketKeys: (f = msg.getSessionTicketKeys()) && envoy_api_v2_auth_common_pb.TlsSessionTicketKeys.toObject(includeInstance, f),
    sessionTicketKeysSdsSecretConfig: (f = msg.getSessionTicketKeysSdsSecretConfig()) && envoy_api_v2_auth_secret_pb.SdsSecretConfig.toObject(includeInstance, f),
    disableStatelessSessionResumption: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    sessionTimeout: (f = msg.getSessionTimeout()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.api.v2.auth.DownstreamTlsContext}
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.api.v2.auth.DownstreamTlsContext;
  return proto.envoy.api.v2.auth.DownstreamTlsContext.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.api.v2.auth.DownstreamTlsContext} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.api.v2.auth.DownstreamTlsContext}
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.envoy.api.v2.auth.CommonTlsContext;
      reader.readMessage(value,proto.envoy.api.v2.auth.CommonTlsContext.deserializeBinaryFromReader);
      msg.setCommonTlsContext(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.BoolValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.BoolValue.deserializeBinaryFromReader);
      msg.setRequireClientCertificate(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.BoolValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.BoolValue.deserializeBinaryFromReader);
      msg.setRequireSni(value);
      break;
    case 4:
      var value = new envoy_api_v2_auth_common_pb.TlsSessionTicketKeys;
      reader.readMessage(value,envoy_api_v2_auth_common_pb.TlsSessionTicketKeys.deserializeBinaryFromReader);
      msg.setSessionTicketKeys(value);
      break;
    case 5:
      var value = new envoy_api_v2_auth_secret_pb.SdsSecretConfig;
      reader.readMessage(value,envoy_api_v2_auth_secret_pb.SdsSecretConfig.deserializeBinaryFromReader);
      msg.setSessionTicketKeysSdsSecretConfig(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDisableStatelessSessionResumption(value);
      break;
    case 6:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setSessionTimeout(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.api.v2.auth.DownstreamTlsContext.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.api.v2.auth.DownstreamTlsContext} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCommonTlsContext();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.envoy.api.v2.auth.CommonTlsContext.serializeBinaryToWriter
    );
  }
  f = message.getRequireClientCertificate();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getRequireSni();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getSessionTicketKeys();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      envoy_api_v2_auth_common_pb.TlsSessionTicketKeys.serializeBinaryToWriter
    );
  }
  f = message.getSessionTicketKeysSdsSecretConfig();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      envoy_api_v2_auth_secret_pb.SdsSecretConfig.serializeBinaryToWriter
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getSessionTimeout();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
};


/**
 * optional CommonTlsContext common_tls_context = 1;
 * @return {?proto.envoy.api.v2.auth.CommonTlsContext}
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.getCommonTlsContext = function() {
  return /** @type{?proto.envoy.api.v2.auth.CommonTlsContext} */ (
    jspb.Message.getWrapperField(this, proto.envoy.api.v2.auth.CommonTlsContext, 1));
};


/**
 * @param {?proto.envoy.api.v2.auth.CommonTlsContext|undefined} value
 * @return {!proto.envoy.api.v2.auth.DownstreamTlsContext} returns this
*/
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.setCommonTlsContext = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.api.v2.auth.DownstreamTlsContext} returns this
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.clearCommonTlsContext = function() {
  return this.setCommonTlsContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.hasCommonTlsContext = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.BoolValue require_client_certificate = 2;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.getRequireClientCertificate = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.BoolValue, 2));
};


/**
 * @param {?proto.google.protobuf.BoolValue|undefined} value
 * @return {!proto.envoy.api.v2.auth.DownstreamTlsContext} returns this
*/
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.setRequireClientCertificate = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.api.v2.auth.DownstreamTlsContext} returns this
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.clearRequireClientCertificate = function() {
  return this.setRequireClientCertificate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.hasRequireClientCertificate = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.BoolValue require_sni = 3;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.getRequireSni = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.BoolValue, 3));
};


/**
 * @param {?proto.google.protobuf.BoolValue|undefined} value
 * @return {!proto.envoy.api.v2.auth.DownstreamTlsContext} returns this
*/
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.setRequireSni = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.api.v2.auth.DownstreamTlsContext} returns this
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.clearRequireSni = function() {
  return this.setRequireSni(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.hasRequireSni = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional TlsSessionTicketKeys session_ticket_keys = 4;
 * @return {?proto.envoy.api.v2.auth.TlsSessionTicketKeys}
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.getSessionTicketKeys = function() {
  return /** @type{?proto.envoy.api.v2.auth.TlsSessionTicketKeys} */ (
    jspb.Message.getWrapperField(this, envoy_api_v2_auth_common_pb.TlsSessionTicketKeys, 4));
};


/**
 * @param {?proto.envoy.api.v2.auth.TlsSessionTicketKeys|undefined} value
 * @return {!proto.envoy.api.v2.auth.DownstreamTlsContext} returns this
*/
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.setSessionTicketKeys = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.envoy.api.v2.auth.DownstreamTlsContext.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.api.v2.auth.DownstreamTlsContext} returns this
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.clearSessionTicketKeys = function() {
  return this.setSessionTicketKeys(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.hasSessionTicketKeys = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional SdsSecretConfig session_ticket_keys_sds_secret_config = 5;
 * @return {?proto.envoy.api.v2.auth.SdsSecretConfig}
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.getSessionTicketKeysSdsSecretConfig = function() {
  return /** @type{?proto.envoy.api.v2.auth.SdsSecretConfig} */ (
    jspb.Message.getWrapperField(this, envoy_api_v2_auth_secret_pb.SdsSecretConfig, 5));
};


/**
 * @param {?proto.envoy.api.v2.auth.SdsSecretConfig|undefined} value
 * @return {!proto.envoy.api.v2.auth.DownstreamTlsContext} returns this
*/
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.setSessionTicketKeysSdsSecretConfig = function(value) {
  return jspb.Message.setOneofWrapperField(this, 5, proto.envoy.api.v2.auth.DownstreamTlsContext.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.api.v2.auth.DownstreamTlsContext} returns this
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.clearSessionTicketKeysSdsSecretConfig = function() {
  return this.setSessionTicketKeysSdsSecretConfig(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.hasSessionTicketKeysSdsSecretConfig = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional bool disable_stateless_session_resumption = 7;
 * @return {boolean}
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.getDisableStatelessSessionResumption = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.envoy.api.v2.auth.DownstreamTlsContext} returns this
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.setDisableStatelessSessionResumption = function(value) {
  return jspb.Message.setOneofField(this, 7, proto.envoy.api.v2.auth.DownstreamTlsContext.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.envoy.api.v2.auth.DownstreamTlsContext} returns this
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.clearDisableStatelessSessionResumption = function() {
  return jspb.Message.setOneofField(this, 7, proto.envoy.api.v2.auth.DownstreamTlsContext.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.hasDisableStatelessSessionResumption = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.Duration session_timeout = 6;
 * @return {?proto.google.protobuf.Duration}
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.getSessionTimeout = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 6));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.envoy.api.v2.auth.DownstreamTlsContext} returns this
*/
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.setSessionTimeout = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.api.v2.auth.DownstreamTlsContext} returns this
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.clearSessionTimeout = function() {
  return this.setSessionTimeout(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.api.v2.auth.DownstreamTlsContext.prototype.hasSessionTimeout = function() {
  return jspb.Message.getField(this, 6) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.envoy.api.v2.auth.CommonTlsContext.repeatedFields_ = [2,6,4];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.envoy.api.v2.auth.CommonTlsContext.oneofGroups_ = [[3,7,8]];

/**
 * @enum {number}
 */
proto.envoy.api.v2.auth.CommonTlsContext.ValidationContextTypeCase = {
  VALIDATION_CONTEXT_TYPE_NOT_SET: 0,
  VALIDATION_CONTEXT: 3,
  VALIDATION_CONTEXT_SDS_SECRET_CONFIG: 7,
  COMBINED_VALIDATION_CONTEXT: 8
};

/**
 * @return {proto.envoy.api.v2.auth.CommonTlsContext.ValidationContextTypeCase}
 */
proto.envoy.api.v2.auth.CommonTlsContext.prototype.getValidationContextTypeCase = function() {
  return /** @type {proto.envoy.api.v2.auth.CommonTlsContext.ValidationContextTypeCase} */(jspb.Message.computeOneofCase(this, proto.envoy.api.v2.auth.CommonTlsContext.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.api.v2.auth.CommonTlsContext.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.api.v2.auth.CommonTlsContext.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.api.v2.auth.CommonTlsContext} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.auth.CommonTlsContext.toObject = function(includeInstance, msg) {
  var f, obj = {
    tlsParams: (f = msg.getTlsParams()) && envoy_api_v2_auth_common_pb.TlsParameters.toObject(includeInstance, f),
    tlsCertificatesList: jspb.Message.toObjectList(msg.getTlsCertificatesList(),
    envoy_api_v2_auth_common_pb.TlsCertificate.toObject, includeInstance),
    tlsCertificateSdsSecretConfigsList: jspb.Message.toObjectList(msg.getTlsCertificateSdsSecretConfigsList(),
    envoy_api_v2_auth_secret_pb.SdsSecretConfig.toObject, includeInstance),
    validationContext: (f = msg.getValidationContext()) && envoy_api_v2_auth_common_pb.CertificateValidationContext.toObject(includeInstance, f),
    validationContextSdsSecretConfig: (f = msg.getValidationContextSdsSecretConfig()) && envoy_api_v2_auth_secret_pb.SdsSecretConfig.toObject(includeInstance, f),
    combinedValidationContext: (f = msg.getCombinedValidationContext()) && proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext.toObject(includeInstance, f),
    alpnProtocolsList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.api.v2.auth.CommonTlsContext}
 */
proto.envoy.api.v2.auth.CommonTlsContext.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.api.v2.auth.CommonTlsContext;
  return proto.envoy.api.v2.auth.CommonTlsContext.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.api.v2.auth.CommonTlsContext} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.api.v2.auth.CommonTlsContext}
 */
proto.envoy.api.v2.auth.CommonTlsContext.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new envoy_api_v2_auth_common_pb.TlsParameters;
      reader.readMessage(value,envoy_api_v2_auth_common_pb.TlsParameters.deserializeBinaryFromReader);
      msg.setTlsParams(value);
      break;
    case 2:
      var value = new envoy_api_v2_auth_common_pb.TlsCertificate;
      reader.readMessage(value,envoy_api_v2_auth_common_pb.TlsCertificate.deserializeBinaryFromReader);
      msg.addTlsCertificates(value);
      break;
    case 6:
      var value = new envoy_api_v2_auth_secret_pb.SdsSecretConfig;
      reader.readMessage(value,envoy_api_v2_auth_secret_pb.SdsSecretConfig.deserializeBinaryFromReader);
      msg.addTlsCertificateSdsSecretConfigs(value);
      break;
    case 3:
      var value = new envoy_api_v2_auth_common_pb.CertificateValidationContext;
      reader.readMessage(value,envoy_api_v2_auth_common_pb.CertificateValidationContext.deserializeBinaryFromReader);
      msg.setValidationContext(value);
      break;
    case 7:
      var value = new envoy_api_v2_auth_secret_pb.SdsSecretConfig;
      reader.readMessage(value,envoy_api_v2_auth_secret_pb.SdsSecretConfig.deserializeBinaryFromReader);
      msg.setValidationContextSdsSecretConfig(value);
      break;
    case 8:
      var value = new proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext;
      reader.readMessage(value,proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext.deserializeBinaryFromReader);
      msg.setCombinedValidationContext(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addAlpnProtocols(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.api.v2.auth.CommonTlsContext.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.api.v2.auth.CommonTlsContext.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.api.v2.auth.CommonTlsContext} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.auth.CommonTlsContext.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTlsParams();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      envoy_api_v2_auth_common_pb.TlsParameters.serializeBinaryToWriter
    );
  }
  f = message.getTlsCertificatesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      envoy_api_v2_auth_common_pb.TlsCertificate.serializeBinaryToWriter
    );
  }
  f = message.getTlsCertificateSdsSecretConfigsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      envoy_api_v2_auth_secret_pb.SdsSecretConfig.serializeBinaryToWriter
    );
  }
  f = message.getValidationContext();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      envoy_api_v2_auth_common_pb.CertificateValidationContext.serializeBinaryToWriter
    );
  }
  f = message.getValidationContextSdsSecretConfig();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      envoy_api_v2_auth_secret_pb.SdsSecretConfig.serializeBinaryToWriter
    );
  }
  f = message.getCombinedValidationContext();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext.serializeBinaryToWriter
    );
  }
  f = message.getAlpnProtocolsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext.toObject = function(includeInstance, msg) {
  var f, obj = {
    defaultValidationContext: (f = msg.getDefaultValidationContext()) && envoy_api_v2_auth_common_pb.CertificateValidationContext.toObject(includeInstance, f),
    validationContextSdsSecretConfig: (f = msg.getValidationContextSdsSecretConfig()) && envoy_api_v2_auth_secret_pb.SdsSecretConfig.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext}
 */
proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext;
  return proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext}
 */
proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new envoy_api_v2_auth_common_pb.CertificateValidationContext;
      reader.readMessage(value,envoy_api_v2_auth_common_pb.CertificateValidationContext.deserializeBinaryFromReader);
      msg.setDefaultValidationContext(value);
      break;
    case 2:
      var value = new envoy_api_v2_auth_secret_pb.SdsSecretConfig;
      reader.readMessage(value,envoy_api_v2_auth_secret_pb.SdsSecretConfig.deserializeBinaryFromReader);
      msg.setValidationContextSdsSecretConfig(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDefaultValidationContext();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      envoy_api_v2_auth_common_pb.CertificateValidationContext.serializeBinaryToWriter
    );
  }
  f = message.getValidationContextSdsSecretConfig();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      envoy_api_v2_auth_secret_pb.SdsSecretConfig.serializeBinaryToWriter
    );
  }
};


/**
 * optional CertificateValidationContext default_validation_context = 1;
 * @return {?proto.envoy.api.v2.auth.CertificateValidationContext}
 */
proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext.prototype.getDefaultValidationContext = function() {
  return /** @type{?proto.envoy.api.v2.auth.CertificateValidationContext} */ (
    jspb.Message.getWrapperField(this, envoy_api_v2_auth_common_pb.CertificateValidationContext, 1));
};


/**
 * @param {?proto.envoy.api.v2.auth.CertificateValidationContext|undefined} value
 * @return {!proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext} returns this
*/
proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext.prototype.setDefaultValidationContext = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext} returns this
 */
proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext.prototype.clearDefaultValidationContext = function() {
  return this.setDefaultValidationContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext.prototype.hasDefaultValidationContext = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional SdsSecretConfig validation_context_sds_secret_config = 2;
 * @return {?proto.envoy.api.v2.auth.SdsSecretConfig}
 */
proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext.prototype.getValidationContextSdsSecretConfig = function() {
  return /** @type{?proto.envoy.api.v2.auth.SdsSecretConfig} */ (
    jspb.Message.getWrapperField(this, envoy_api_v2_auth_secret_pb.SdsSecretConfig, 2));
};


/**
 * @param {?proto.envoy.api.v2.auth.SdsSecretConfig|undefined} value
 * @return {!proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext} returns this
*/
proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext.prototype.setValidationContextSdsSecretConfig = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext} returns this
 */
proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext.prototype.clearValidationContextSdsSecretConfig = function() {
  return this.setValidationContextSdsSecretConfig(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext.prototype.hasValidationContextSdsSecretConfig = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional TlsParameters tls_params = 1;
 * @return {?proto.envoy.api.v2.auth.TlsParameters}
 */
proto.envoy.api.v2.auth.CommonTlsContext.prototype.getTlsParams = function() {
  return /** @type{?proto.envoy.api.v2.auth.TlsParameters} */ (
    jspb.Message.getWrapperField(this, envoy_api_v2_auth_common_pb.TlsParameters, 1));
};


/**
 * @param {?proto.envoy.api.v2.auth.TlsParameters|undefined} value
 * @return {!proto.envoy.api.v2.auth.CommonTlsContext} returns this
*/
proto.envoy.api.v2.auth.CommonTlsContext.prototype.setTlsParams = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.api.v2.auth.CommonTlsContext} returns this
 */
proto.envoy.api.v2.auth.CommonTlsContext.prototype.clearTlsParams = function() {
  return this.setTlsParams(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.api.v2.auth.CommonTlsContext.prototype.hasTlsParams = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated TlsCertificate tls_certificates = 2;
 * @return {!Array<!proto.envoy.api.v2.auth.TlsCertificate>}
 */
proto.envoy.api.v2.auth.CommonTlsContext.prototype.getTlsCertificatesList = function() {
  return /** @type{!Array<!proto.envoy.api.v2.auth.TlsCertificate>} */ (
    jspb.Message.getRepeatedWrapperField(this, envoy_api_v2_auth_common_pb.TlsCertificate, 2));
};


/**
 * @param {!Array<!proto.envoy.api.v2.auth.TlsCertificate>} value
 * @return {!proto.envoy.api.v2.auth.CommonTlsContext} returns this
*/
proto.envoy.api.v2.auth.CommonTlsContext.prototype.setTlsCertificatesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.envoy.api.v2.auth.TlsCertificate=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.api.v2.auth.TlsCertificate}
 */
proto.envoy.api.v2.auth.CommonTlsContext.prototype.addTlsCertificates = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.envoy.api.v2.auth.TlsCertificate, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.envoy.api.v2.auth.CommonTlsContext} returns this
 */
proto.envoy.api.v2.auth.CommonTlsContext.prototype.clearTlsCertificatesList = function() {
  return this.setTlsCertificatesList([]);
};


/**
 * repeated SdsSecretConfig tls_certificate_sds_secret_configs = 6;
 * @return {!Array<!proto.envoy.api.v2.auth.SdsSecretConfig>}
 */
proto.envoy.api.v2.auth.CommonTlsContext.prototype.getTlsCertificateSdsSecretConfigsList = function() {
  return /** @type{!Array<!proto.envoy.api.v2.auth.SdsSecretConfig>} */ (
    jspb.Message.getRepeatedWrapperField(this, envoy_api_v2_auth_secret_pb.SdsSecretConfig, 6));
};


/**
 * @param {!Array<!proto.envoy.api.v2.auth.SdsSecretConfig>} value
 * @return {!proto.envoy.api.v2.auth.CommonTlsContext} returns this
*/
proto.envoy.api.v2.auth.CommonTlsContext.prototype.setTlsCertificateSdsSecretConfigsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.envoy.api.v2.auth.SdsSecretConfig=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.api.v2.auth.SdsSecretConfig}
 */
proto.envoy.api.v2.auth.CommonTlsContext.prototype.addTlsCertificateSdsSecretConfigs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.envoy.api.v2.auth.SdsSecretConfig, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.envoy.api.v2.auth.CommonTlsContext} returns this
 */
proto.envoy.api.v2.auth.CommonTlsContext.prototype.clearTlsCertificateSdsSecretConfigsList = function() {
  return this.setTlsCertificateSdsSecretConfigsList([]);
};


/**
 * optional CertificateValidationContext validation_context = 3;
 * @return {?proto.envoy.api.v2.auth.CertificateValidationContext}
 */
proto.envoy.api.v2.auth.CommonTlsContext.prototype.getValidationContext = function() {
  return /** @type{?proto.envoy.api.v2.auth.CertificateValidationContext} */ (
    jspb.Message.getWrapperField(this, envoy_api_v2_auth_common_pb.CertificateValidationContext, 3));
};


/**
 * @param {?proto.envoy.api.v2.auth.CertificateValidationContext|undefined} value
 * @return {!proto.envoy.api.v2.auth.CommonTlsContext} returns this
*/
proto.envoy.api.v2.auth.CommonTlsContext.prototype.setValidationContext = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.envoy.api.v2.auth.CommonTlsContext.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.api.v2.auth.CommonTlsContext} returns this
 */
proto.envoy.api.v2.auth.CommonTlsContext.prototype.clearValidationContext = function() {
  return this.setValidationContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.api.v2.auth.CommonTlsContext.prototype.hasValidationContext = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional SdsSecretConfig validation_context_sds_secret_config = 7;
 * @return {?proto.envoy.api.v2.auth.SdsSecretConfig}
 */
proto.envoy.api.v2.auth.CommonTlsContext.prototype.getValidationContextSdsSecretConfig = function() {
  return /** @type{?proto.envoy.api.v2.auth.SdsSecretConfig} */ (
    jspb.Message.getWrapperField(this, envoy_api_v2_auth_secret_pb.SdsSecretConfig, 7));
};


/**
 * @param {?proto.envoy.api.v2.auth.SdsSecretConfig|undefined} value
 * @return {!proto.envoy.api.v2.auth.CommonTlsContext} returns this
*/
proto.envoy.api.v2.auth.CommonTlsContext.prototype.setValidationContextSdsSecretConfig = function(value) {
  return jspb.Message.setOneofWrapperField(this, 7, proto.envoy.api.v2.auth.CommonTlsContext.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.api.v2.auth.CommonTlsContext} returns this
 */
proto.envoy.api.v2.auth.CommonTlsContext.prototype.clearValidationContextSdsSecretConfig = function() {
  return this.setValidationContextSdsSecretConfig(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.api.v2.auth.CommonTlsContext.prototype.hasValidationContextSdsSecretConfig = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional CombinedCertificateValidationContext combined_validation_context = 8;
 * @return {?proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext}
 */
proto.envoy.api.v2.auth.CommonTlsContext.prototype.getCombinedValidationContext = function() {
  return /** @type{?proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext} */ (
    jspb.Message.getWrapperField(this, proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext, 8));
};


/**
 * @param {?proto.envoy.api.v2.auth.CommonTlsContext.CombinedCertificateValidationContext|undefined} value
 * @return {!proto.envoy.api.v2.auth.CommonTlsContext} returns this
*/
proto.envoy.api.v2.auth.CommonTlsContext.prototype.setCombinedValidationContext = function(value) {
  return jspb.Message.setOneofWrapperField(this, 8, proto.envoy.api.v2.auth.CommonTlsContext.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.api.v2.auth.CommonTlsContext} returns this
 */
proto.envoy.api.v2.auth.CommonTlsContext.prototype.clearCombinedValidationContext = function() {
  return this.setCombinedValidationContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.api.v2.auth.CommonTlsContext.prototype.hasCombinedValidationContext = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * repeated string alpn_protocols = 4;
 * @return {!Array<string>}
 */
proto.envoy.api.v2.auth.CommonTlsContext.prototype.getAlpnProtocolsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.envoy.api.v2.auth.CommonTlsContext} returns this
 */
proto.envoy.api.v2.auth.CommonTlsContext.prototype.setAlpnProtocolsList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.envoy.api.v2.auth.CommonTlsContext} returns this
 */
proto.envoy.api.v2.auth.CommonTlsContext.prototype.addAlpnProtocols = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.envoy.api.v2.auth.CommonTlsContext} returns this
 */
proto.envoy.api.v2.auth.CommonTlsContext.prototype.clearAlpnProtocolsList = function() {
  return this.setAlpnProtocolsList([]);
};


goog.object.extend(exports, proto.envoy.api.v2.auth);
