version: '2'
services:
  xds:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./example:/app/example
      - ./src:/app/src
      - ./lib:/app/lib
      - ./package.json:/app/package.json
    environment: 
      - "SERVICE_A=10.5.0.5"
      - "SERVICE_B=10.5.0.6"
    working_dir: /app
    command: npm run example
    ports:
      - "5000:5000"
    networks:
      envoymesh:
        aliases:
          - xds
  
  service-a:
    image: node:alpine
    working_dir: /opt/app
    volumes:
      - ./example/service-a.js:/opt/app/index.js
    command: node index.js
    ports:
      - "3001:3000"
    networks:
      envoymesh:
        ipv4_address: 10.5.0.5
        aliases:
          - service_a

  service-b:
    image: node:alpine
    working_dir: /opt/app
    volumes:
      - ./example/service-b.js:/opt/app/index.js
    command: node index.js
    ports:
      - "3002:3000"
    networks:
      envoymesh:
        ipv4_address: 10.5.0.6
        
  proxy-1:
    image: envoyproxy/envoy:latest
    volumes:
      - ./example/proxy-1.yaml:/etc/envoy.yaml
    ports:
      - "8080:80"
      - "8001:8001"
    command: /usr/local/bin/envoy -c /etc/envoy.yaml
    networks:
      - envoymesh

networks:
  envoymesh: 
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
