// source: envoy/service/auth/v3/external_auth.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var envoy_config_core_v3_base_pb = require('../../../../envoy/config/core/v3/base_pb.js');
goog.object.extend(proto, envoy_config_core_v3_base_pb);
var envoy_service_auth_v3_attribute_context_pb = require('../../../../envoy/service/auth/v3/attribute_context_pb.js');
goog.object.extend(proto, envoy_service_auth_v3_attribute_context_pb);
var envoy_type_v3_http_status_pb = require('../../../../envoy/type/v3/http_status_pb.js');
goog.object.extend(proto, envoy_type_v3_http_status_pb);
var google_protobuf_struct_pb = require('google-protobuf/google/protobuf/struct_pb.js');
goog.object.extend(proto, google_protobuf_struct_pb);
var google_rpc_status_pb = require('../../../../google/rpc/status_pb.js');
goog.object.extend(proto, google_rpc_status_pb);
var udpa_annotations_status_pb = require('../../../../udpa/annotations/status_pb.js');
goog.object.extend(proto, udpa_annotations_status_pb);
var udpa_annotations_versioning_pb = require('../../../../udpa/annotations/versioning_pb.js');
goog.object.extend(proto, udpa_annotations_versioning_pb);
var validate_validate_pb = require('../../../../validate/validate_pb.js');
goog.object.extend(proto, validate_validate_pb);
goog.exportSymbol('proto.envoy.service.auth.v3.CheckRequest', null, global);
goog.exportSymbol('proto.envoy.service.auth.v3.CheckResponse', null, global);
goog.exportSymbol('proto.envoy.service.auth.v3.CheckResponse.HttpResponseCase', null, global);
goog.exportSymbol('proto.envoy.service.auth.v3.DeniedHttpResponse', null, global);
goog.exportSymbol('proto.envoy.service.auth.v3.OkHttpResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.service.auth.v3.CheckRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.envoy.service.auth.v3.CheckRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.service.auth.v3.CheckRequest.displayName = 'proto.envoy.service.auth.v3.CheckRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.service.auth.v3.DeniedHttpResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.envoy.service.auth.v3.DeniedHttpResponse.repeatedFields_, null);
};
goog.inherits(proto.envoy.service.auth.v3.DeniedHttpResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.service.auth.v3.DeniedHttpResponse.displayName = 'proto.envoy.service.auth.v3.DeniedHttpResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.service.auth.v3.OkHttpResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.envoy.service.auth.v3.OkHttpResponse.repeatedFields_, null);
};
goog.inherits(proto.envoy.service.auth.v3.OkHttpResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.service.auth.v3.OkHttpResponse.displayName = 'proto.envoy.service.auth.v3.OkHttpResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.envoy.service.auth.v3.CheckResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.envoy.service.auth.v3.CheckResponse.oneofGroups_);
};
goog.inherits(proto.envoy.service.auth.v3.CheckResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.envoy.service.auth.v3.CheckResponse.displayName = 'proto.envoy.service.auth.v3.CheckResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.service.auth.v3.CheckRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.service.auth.v3.CheckRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.service.auth.v3.CheckRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.service.auth.v3.CheckRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    attributes: (f = msg.getAttributes()) && envoy_service_auth_v3_attribute_context_pb.AttributeContext.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.service.auth.v3.CheckRequest}
 */
proto.envoy.service.auth.v3.CheckRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.service.auth.v3.CheckRequest;
  return proto.envoy.service.auth.v3.CheckRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.service.auth.v3.CheckRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.service.auth.v3.CheckRequest}
 */
proto.envoy.service.auth.v3.CheckRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new envoy_service_auth_v3_attribute_context_pb.AttributeContext;
      reader.readMessage(value,envoy_service_auth_v3_attribute_context_pb.AttributeContext.deserializeBinaryFromReader);
      msg.setAttributes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.service.auth.v3.CheckRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.service.auth.v3.CheckRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.service.auth.v3.CheckRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.service.auth.v3.CheckRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAttributes();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      envoy_service_auth_v3_attribute_context_pb.AttributeContext.serializeBinaryToWriter
    );
  }
};


/**
 * optional AttributeContext attributes = 1;
 * @return {?proto.envoy.service.auth.v3.AttributeContext}
 */
proto.envoy.service.auth.v3.CheckRequest.prototype.getAttributes = function() {
  return /** @type{?proto.envoy.service.auth.v3.AttributeContext} */ (
    jspb.Message.getWrapperField(this, envoy_service_auth_v3_attribute_context_pb.AttributeContext, 1));
};


/**
 * @param {?proto.envoy.service.auth.v3.AttributeContext|undefined} value
 * @return {!proto.envoy.service.auth.v3.CheckRequest} returns this
*/
proto.envoy.service.auth.v3.CheckRequest.prototype.setAttributes = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.service.auth.v3.CheckRequest} returns this
 */
proto.envoy.service.auth.v3.CheckRequest.prototype.clearAttributes = function() {
  return this.setAttributes(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.service.auth.v3.CheckRequest.prototype.hasAttributes = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.envoy.service.auth.v3.DeniedHttpResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.service.auth.v3.DeniedHttpResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.service.auth.v3.DeniedHttpResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.service.auth.v3.DeniedHttpResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.service.auth.v3.DeniedHttpResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: (f = msg.getStatus()) && envoy_type_v3_http_status_pb.HttpStatus.toObject(includeInstance, f),
    headersList: jspb.Message.toObjectList(msg.getHeadersList(),
    envoy_config_core_v3_base_pb.HeaderValueOption.toObject, includeInstance),
    body: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.service.auth.v3.DeniedHttpResponse}
 */
proto.envoy.service.auth.v3.DeniedHttpResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.service.auth.v3.DeniedHttpResponse;
  return proto.envoy.service.auth.v3.DeniedHttpResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.service.auth.v3.DeniedHttpResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.service.auth.v3.DeniedHttpResponse}
 */
proto.envoy.service.auth.v3.DeniedHttpResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new envoy_type_v3_http_status_pb.HttpStatus;
      reader.readMessage(value,envoy_type_v3_http_status_pb.HttpStatus.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 2:
      var value = new envoy_config_core_v3_base_pb.HeaderValueOption;
      reader.readMessage(value,envoy_config_core_v3_base_pb.HeaderValueOption.deserializeBinaryFromReader);
      msg.addHeaders(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setBody(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.service.auth.v3.DeniedHttpResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.service.auth.v3.DeniedHttpResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.service.auth.v3.DeniedHttpResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.service.auth.v3.DeniedHttpResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      envoy_type_v3_http_status_pb.HttpStatus.serializeBinaryToWriter
    );
  }
  f = message.getHeadersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      envoy_config_core_v3_base_pb.HeaderValueOption.serializeBinaryToWriter
    );
  }
  f = message.getBody();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional envoy.type.v3.HttpStatus status = 1;
 * @return {?proto.envoy.type.v3.HttpStatus}
 */
proto.envoy.service.auth.v3.DeniedHttpResponse.prototype.getStatus = function() {
  return /** @type{?proto.envoy.type.v3.HttpStatus} */ (
    jspb.Message.getWrapperField(this, envoy_type_v3_http_status_pb.HttpStatus, 1));
};


/**
 * @param {?proto.envoy.type.v3.HttpStatus|undefined} value
 * @return {!proto.envoy.service.auth.v3.DeniedHttpResponse} returns this
*/
proto.envoy.service.auth.v3.DeniedHttpResponse.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.service.auth.v3.DeniedHttpResponse} returns this
 */
proto.envoy.service.auth.v3.DeniedHttpResponse.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.service.auth.v3.DeniedHttpResponse.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated envoy.config.core.v3.HeaderValueOption headers = 2;
 * @return {!Array<!proto.envoy.config.core.v3.HeaderValueOption>}
 */
proto.envoy.service.auth.v3.DeniedHttpResponse.prototype.getHeadersList = function() {
  return /** @type{!Array<!proto.envoy.config.core.v3.HeaderValueOption>} */ (
    jspb.Message.getRepeatedWrapperField(this, envoy_config_core_v3_base_pb.HeaderValueOption, 2));
};


/**
 * @param {!Array<!proto.envoy.config.core.v3.HeaderValueOption>} value
 * @return {!proto.envoy.service.auth.v3.DeniedHttpResponse} returns this
*/
proto.envoy.service.auth.v3.DeniedHttpResponse.prototype.setHeadersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.envoy.config.core.v3.HeaderValueOption=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.config.core.v3.HeaderValueOption}
 */
proto.envoy.service.auth.v3.DeniedHttpResponse.prototype.addHeaders = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.envoy.config.core.v3.HeaderValueOption, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.envoy.service.auth.v3.DeniedHttpResponse} returns this
 */
proto.envoy.service.auth.v3.DeniedHttpResponse.prototype.clearHeadersList = function() {
  return this.setHeadersList([]);
};


/**
 * optional string body = 3;
 * @return {string}
 */
proto.envoy.service.auth.v3.DeniedHttpResponse.prototype.getBody = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.envoy.service.auth.v3.DeniedHttpResponse} returns this
 */
proto.envoy.service.auth.v3.DeniedHttpResponse.prototype.setBody = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.envoy.service.auth.v3.OkHttpResponse.repeatedFields_ = [2,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.service.auth.v3.OkHttpResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.service.auth.v3.OkHttpResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.service.auth.v3.OkHttpResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.service.auth.v3.OkHttpResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    headersList: jspb.Message.toObjectList(msg.getHeadersList(),
    envoy_config_core_v3_base_pb.HeaderValueOption.toObject, includeInstance),
    headersToRemoveList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f,
    dynamicMetadata: (f = msg.getDynamicMetadata()) && google_protobuf_struct_pb.Struct.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.service.auth.v3.OkHttpResponse}
 */
proto.envoy.service.auth.v3.OkHttpResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.service.auth.v3.OkHttpResponse;
  return proto.envoy.service.auth.v3.OkHttpResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.service.auth.v3.OkHttpResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.service.auth.v3.OkHttpResponse}
 */
proto.envoy.service.auth.v3.OkHttpResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new envoy_config_core_v3_base_pb.HeaderValueOption;
      reader.readMessage(value,envoy_config_core_v3_base_pb.HeaderValueOption.deserializeBinaryFromReader);
      msg.addHeaders(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addHeadersToRemove(value);
      break;
    case 3:
      var value = new google_protobuf_struct_pb.Struct;
      reader.readMessage(value,google_protobuf_struct_pb.Struct.deserializeBinaryFromReader);
      msg.setDynamicMetadata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.service.auth.v3.OkHttpResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.service.auth.v3.OkHttpResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.service.auth.v3.OkHttpResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.service.auth.v3.OkHttpResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeadersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      envoy_config_core_v3_base_pb.HeaderValueOption.serializeBinaryToWriter
    );
  }
  f = message.getHeadersToRemoveList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
  f = message.getDynamicMetadata();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_struct_pb.Struct.serializeBinaryToWriter
    );
  }
};


/**
 * repeated envoy.config.core.v3.HeaderValueOption headers = 2;
 * @return {!Array<!proto.envoy.config.core.v3.HeaderValueOption>}
 */
proto.envoy.service.auth.v3.OkHttpResponse.prototype.getHeadersList = function() {
  return /** @type{!Array<!proto.envoy.config.core.v3.HeaderValueOption>} */ (
    jspb.Message.getRepeatedWrapperField(this, envoy_config_core_v3_base_pb.HeaderValueOption, 2));
};


/**
 * @param {!Array<!proto.envoy.config.core.v3.HeaderValueOption>} value
 * @return {!proto.envoy.service.auth.v3.OkHttpResponse} returns this
*/
proto.envoy.service.auth.v3.OkHttpResponse.prototype.setHeadersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.envoy.config.core.v3.HeaderValueOption=} opt_value
 * @param {number=} opt_index
 * @return {!proto.envoy.config.core.v3.HeaderValueOption}
 */
proto.envoy.service.auth.v3.OkHttpResponse.prototype.addHeaders = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.envoy.config.core.v3.HeaderValueOption, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.envoy.service.auth.v3.OkHttpResponse} returns this
 */
proto.envoy.service.auth.v3.OkHttpResponse.prototype.clearHeadersList = function() {
  return this.setHeadersList([]);
};


/**
 * repeated string headers_to_remove = 5;
 * @return {!Array<string>}
 */
proto.envoy.service.auth.v3.OkHttpResponse.prototype.getHeadersToRemoveList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.envoy.service.auth.v3.OkHttpResponse} returns this
 */
proto.envoy.service.auth.v3.OkHttpResponse.prototype.setHeadersToRemoveList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.envoy.service.auth.v3.OkHttpResponse} returns this
 */
proto.envoy.service.auth.v3.OkHttpResponse.prototype.addHeadersToRemove = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.envoy.service.auth.v3.OkHttpResponse} returns this
 */
proto.envoy.service.auth.v3.OkHttpResponse.prototype.clearHeadersToRemoveList = function() {
  return this.setHeadersToRemoveList([]);
};


/**
 * optional google.protobuf.Struct dynamic_metadata = 3;
 * @return {?proto.google.protobuf.Struct}
 */
proto.envoy.service.auth.v3.OkHttpResponse.prototype.getDynamicMetadata = function() {
  return /** @type{?proto.google.protobuf.Struct} */ (
    jspb.Message.getWrapperField(this, google_protobuf_struct_pb.Struct, 3));
};


/**
 * @param {?proto.google.protobuf.Struct|undefined} value
 * @return {!proto.envoy.service.auth.v3.OkHttpResponse} returns this
*/
proto.envoy.service.auth.v3.OkHttpResponse.prototype.setDynamicMetadata = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.service.auth.v3.OkHttpResponse} returns this
 */
proto.envoy.service.auth.v3.OkHttpResponse.prototype.clearDynamicMetadata = function() {
  return this.setDynamicMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.service.auth.v3.OkHttpResponse.prototype.hasDynamicMetadata = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.envoy.service.auth.v3.CheckResponse.oneofGroups_ = [[2,3]];

/**
 * @enum {number}
 */
proto.envoy.service.auth.v3.CheckResponse.HttpResponseCase = {
  HTTP_RESPONSE_NOT_SET: 0,
  DENIED_RESPONSE: 2,
  OK_RESPONSE: 3
};

/**
 * @return {proto.envoy.service.auth.v3.CheckResponse.HttpResponseCase}
 */
proto.envoy.service.auth.v3.CheckResponse.prototype.getHttpResponseCase = function() {
  return /** @type {proto.envoy.service.auth.v3.CheckResponse.HttpResponseCase} */(jspb.Message.computeOneofCase(this, proto.envoy.service.auth.v3.CheckResponse.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.envoy.service.auth.v3.CheckResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.envoy.service.auth.v3.CheckResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.envoy.service.auth.v3.CheckResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.service.auth.v3.CheckResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: (f = msg.getStatus()) && google_rpc_status_pb.Status.toObject(includeInstance, f),
    deniedResponse: (f = msg.getDeniedResponse()) && proto.envoy.service.auth.v3.DeniedHttpResponse.toObject(includeInstance, f),
    okResponse: (f = msg.getOkResponse()) && proto.envoy.service.auth.v3.OkHttpResponse.toObject(includeInstance, f),
    dynamicMetadata: (f = msg.getDynamicMetadata()) && google_protobuf_struct_pb.Struct.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.envoy.service.auth.v3.CheckResponse}
 */
proto.envoy.service.auth.v3.CheckResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.envoy.service.auth.v3.CheckResponse;
  return proto.envoy.service.auth.v3.CheckResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.envoy.service.auth.v3.CheckResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.envoy.service.auth.v3.CheckResponse}
 */
proto.envoy.service.auth.v3.CheckResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_rpc_status_pb.Status;
      reader.readMessage(value,google_rpc_status_pb.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 2:
      var value = new proto.envoy.service.auth.v3.DeniedHttpResponse;
      reader.readMessage(value,proto.envoy.service.auth.v3.DeniedHttpResponse.deserializeBinaryFromReader);
      msg.setDeniedResponse(value);
      break;
    case 3:
      var value = new proto.envoy.service.auth.v3.OkHttpResponse;
      reader.readMessage(value,proto.envoy.service.auth.v3.OkHttpResponse.deserializeBinaryFromReader);
      msg.setOkResponse(value);
      break;
    case 4:
      var value = new google_protobuf_struct_pb.Struct;
      reader.readMessage(value,google_protobuf_struct_pb.Struct.deserializeBinaryFromReader);
      msg.setDynamicMetadata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.envoy.service.auth.v3.CheckResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.envoy.service.auth.v3.CheckResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.envoy.service.auth.v3.CheckResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.envoy.service.auth.v3.CheckResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_rpc_status_pb.Status.serializeBinaryToWriter
    );
  }
  f = message.getDeniedResponse();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.envoy.service.auth.v3.DeniedHttpResponse.serializeBinaryToWriter
    );
  }
  f = message.getOkResponse();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.envoy.service.auth.v3.OkHttpResponse.serializeBinaryToWriter
    );
  }
  f = message.getDynamicMetadata();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_struct_pb.Struct.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.rpc.Status status = 1;
 * @return {?proto.google.rpc.Status}
 */
proto.envoy.service.auth.v3.CheckResponse.prototype.getStatus = function() {
  return /** @type{?proto.google.rpc.Status} */ (
    jspb.Message.getWrapperField(this, google_rpc_status_pb.Status, 1));
};


/**
 * @param {?proto.google.rpc.Status|undefined} value
 * @return {!proto.envoy.service.auth.v3.CheckResponse} returns this
*/
proto.envoy.service.auth.v3.CheckResponse.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.service.auth.v3.CheckResponse} returns this
 */
proto.envoy.service.auth.v3.CheckResponse.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.service.auth.v3.CheckResponse.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional DeniedHttpResponse denied_response = 2;
 * @return {?proto.envoy.service.auth.v3.DeniedHttpResponse}
 */
proto.envoy.service.auth.v3.CheckResponse.prototype.getDeniedResponse = function() {
  return /** @type{?proto.envoy.service.auth.v3.DeniedHttpResponse} */ (
    jspb.Message.getWrapperField(this, proto.envoy.service.auth.v3.DeniedHttpResponse, 2));
};


/**
 * @param {?proto.envoy.service.auth.v3.DeniedHttpResponse|undefined} value
 * @return {!proto.envoy.service.auth.v3.CheckResponse} returns this
*/
proto.envoy.service.auth.v3.CheckResponse.prototype.setDeniedResponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.envoy.service.auth.v3.CheckResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.service.auth.v3.CheckResponse} returns this
 */
proto.envoy.service.auth.v3.CheckResponse.prototype.clearDeniedResponse = function() {
  return this.setDeniedResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.service.auth.v3.CheckResponse.prototype.hasDeniedResponse = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional OkHttpResponse ok_response = 3;
 * @return {?proto.envoy.service.auth.v3.OkHttpResponse}
 */
proto.envoy.service.auth.v3.CheckResponse.prototype.getOkResponse = function() {
  return /** @type{?proto.envoy.service.auth.v3.OkHttpResponse} */ (
    jspb.Message.getWrapperField(this, proto.envoy.service.auth.v3.OkHttpResponse, 3));
};


/**
 * @param {?proto.envoy.service.auth.v3.OkHttpResponse|undefined} value
 * @return {!proto.envoy.service.auth.v3.CheckResponse} returns this
*/
proto.envoy.service.auth.v3.CheckResponse.prototype.setOkResponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.envoy.service.auth.v3.CheckResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.service.auth.v3.CheckResponse} returns this
 */
proto.envoy.service.auth.v3.CheckResponse.prototype.clearOkResponse = function() {
  return this.setOkResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.service.auth.v3.CheckResponse.prototype.hasOkResponse = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.Struct dynamic_metadata = 4;
 * @return {?proto.google.protobuf.Struct}
 */
proto.envoy.service.auth.v3.CheckResponse.prototype.getDynamicMetadata = function() {
  return /** @type{?proto.google.protobuf.Struct} */ (
    jspb.Message.getWrapperField(this, google_protobuf_struct_pb.Struct, 4));
};


/**
 * @param {?proto.google.protobuf.Struct|undefined} value
 * @return {!proto.envoy.service.auth.v3.CheckResponse} returns this
*/
proto.envoy.service.auth.v3.CheckResponse.prototype.setDynamicMetadata = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.envoy.service.auth.v3.CheckResponse} returns this
 */
proto.envoy.service.auth.v3.CheckResponse.prototype.clearDynamicMetadata = function() {
  return this.setDynamicMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.envoy.service.auth.v3.CheckResponse.prototype.hasDynamicMetadata = function() {
  return jspb.Message.getField(this, 4) != null;
};


goog.object.extend(exports, proto.envoy.service.auth.v3);
